#!/usr/bin/env python3
"""Run a compact, deterministic MM304 pre-HAC regression matrix.

The cases are generated by generate_mm305_condition_matrix.py and selected to
cover four headings, two crossrange signs, low/high altitude and low/high speed.
The runner records simulator outcomes without changing guidance or admission
state.  It is intentionally separate from the full Cartesian matrix generator so
future changes have a quick, executable acceptance subset.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX = ROOT / "ShuttleSim/scenarios/mm304-regression-matrix"
CASES = [
    "mm305-hac-repro-h0-a20000-v400-e-30000-n0.ini",
    "mm305-hac-repro-h0-a30000-v1300-e0-n30000.ini",
    "mm305-hac-repro-h90-a20000-v400-e-30000-n0.ini",
    "mm305-hac-repro-h90-a30000-v1300-e0-n30000.ini",
    "mm305-hac-repro-h180-a20000-v400-e-30000-n0.ini",
    "mm305-hac-repro-h180-a30000-v1300-e0-n30000.ini",
    "mm305-hac-repro-h270-a20000-v400-e-30000-n0.ini",
    "mm305-hac-repro-h270-a30000-v1300-e0-n30000.ini",
]


def run_case(name: str, max_sim_time: float, plan_timeout: float) -> dict:
    scenario = MATRIX / name
    if not scenario.exists():
        return {"case": name, "status": "missing_scenario"}
    label = "mm304-regression-" + scenario.stem
    cmd = [
        sys.executable, str(ROOT / "ShuttleSim/scripts/run_guidance.py"),
        "--scenario", str(scenario), "--max-sim-time", str(max_sim_time),
        "--plan-timeout", str(plan_timeout), "--label", label,
        "--skip-build", "--no-mirror", "--quiet-progress",
        "--compact-guidance-log",
    ]
    try:
        proc = subprocess.run(cmd, cwd=ROOT, text=True,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              timeout=max_sim_time * 4 + 120)
    except subprocess.TimeoutExpired as exc:
        return {"case": name, "status": "runner_timeout",
                "stdout": exc.stdout or "", "stderr": exc.stderr or ""}
    records = []
    for line in proc.stdout.splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict) and "success" in value:
            records.append(value)
    result = records[-1] if records else {
        "success": False, "abortReason": "no simulator result record",
        "returncode": proc.returncode,
    }
    result["case"] = name
    result["status"] = "pass" if result.get("success") else "fail"
    result["returncode"] = proc.returncode
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-sim-time", type=float, default=120.0)
    ap.add_argument("--plan-timeout", type=float, default=30.0)
    ap.add_argument("--output", type=pathlib.Path)
    args = ap.parse_args()
    results = [run_case(name, args.max_sim_time, args.plan_timeout)
               for name in CASES]
    document = {
        "suite": "mm304-pre-hac-regression",
        "coverage": ["north", "south", "east", "west", "crossrange-left",
                     "crossrange-right", "low-altitude", "high-altitude",
                     "low-speed", "high-speed"],
        "results": results,
    }
    text = json.dumps(document, indent=2, sort_keys=True)
    print(text)
    if args.output:
        args.output.write_text(text + "\n")
    return 0 if all(r.get("status") == "pass" for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
